**Setup**

In [2]:
%pip install sdv

Collecting sdv
  Downloading sdv-1.12.0-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.0/133.0 kB 3.1 MB/s eta 0:00:00
Collecting boto3>=1.28 (from sdv)
  Downloading boto3-1.34.85-py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 7.9 MB/s eta 0:00:00
Collecting botocore>=1.31 (from sdv)
  Downloading botocore-1.34.85-py3-none-any.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 26.7 MB/s eta 0:00:00
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (2.2.1)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from sdv) (0.20.3)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.10/dist-packages (from sdv) (4.66.2)
Collecting copulas>=0.11.0 (from sdv)
  Downloading copulas-0.11.0-py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 kB 7.5 MB/s eta 0:00:00
Collecting ctgan>=0.10.0 (from sdv)
  Downloading ctgan-0.10.0-py3-none-any.whl (24 kB)
Collecting deepecho>=0.6.0 (from sdv)
  Downloading deepecho-0.6.0-py3-none-any.whl (27 kB)
Collecting rdt>=1.11.0 (from sdv)
  Downloading rdt-1.11.1-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 kB 6.6 MB/s eta 0:00:00
Collecting sdmetrics>=0.14.0 (from sdv)
  Downloading sdmetrics-0.14.0-py3-none-any.whl (169 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.9/169.9 kB 22.1 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.4 in /usr/local/lib/python3.10/dist-packages (from sdv) (2.0.3)
Requirement already satisfied: numpy<2,>=1.23.3 in /usr/local/lib/python3.10/dist-packages (from sdv) (1.25.2)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.28->sdv)
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.11.0,>=0.10.0 (from boto3>=1.28->sdv)
  Downloading s3transfer-0.10.1-py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.2/82.2 kB 12.0 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/dist-packages (from botocore>=1.31->sdv) (2.8.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/dist-packages (from botocore>=1.31->sdv) (2.0.7)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.10/dist-packages (from copulas>=0.11.0->sdv) (5.15.0)
Requirement already satisfied: scipy>=1.9.2 in /usr/local/lib/python3.10/dist-packages (from copulas>=0.11.0->sdv) (1.11.4)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from ctgan>=0.10.0->sdv) (2.2.1+cu121)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.4->sdv) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.4->sdv) (2024.1)
Collecting Faker>=17 (from rdt>=1.11.0->sdv)
  Downloading Faker-24.9.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 40.0 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from rdt>=1.11.0->sdv) (1.2.2)
Collecting plotly>=5.10.0 (from copulas>=0.11.0->sdv)
  Downloading plotly-5.20.0-py3-none-any.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 52.6 MB/s eta 0:00:00
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=5.10.0->copulas>=0.11.0->sdv) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=5.10.0->copulas>=0.11.0->sdv) (24.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.31->sdv) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.1.0->rdt>=1.11.0->sdv) (1.4.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.1.0->rdt>=1.11.0->sdv) (3.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (3.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (4.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (2.2.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->ctgan>=0.10.0->sdv)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->ctgan>=0.10.0->sdv) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->ctgan>=0.10.0->sdv) (1.3.0)
Installing collected packages: plotly, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, jmespath, nvidia-cusparse-cu12, nvidia-cudnn-cu12, Faker, botocore, s3transfer, rdt, nvidia-cusolver-cu12, copulas, sdmetrics, boto3, deepecho, ctgan, sdv
  Attempting uninstall: plotly
    Found existing installation: plotly 5.15.0
    Uninstalling plotly-5.15.0:
      Successfully uninstalled plotly-5.15.0
Successfully installed Faker-24.9.0 boto3-1.34.85 botocore-1.34.85 copulas-0.11.0 ctgan-0.10.0 deepecho-0.6.0 jmespath-1.0.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.1.105 plotly-5.20.0 rdt-1.11.1 s3transfer-0.10.1 sdmetrics-0.14.0 sdv-1.12.0

**Import Demos**

In [3]:
from sdv.datasets.demo import get_available_demos
get_available_demos(modality='multi_table')

             dataset_name  size_MB  num_tables
0            Accidents_v1   219.33           3
1      Atherosclerosis_v1     6.62           4
2   AustralianFootball_v1    31.18           4
3     Biodegradability_v1     0.57           5
4                 Bupa_v1     0.04           9
5                 CORA_v1     1.79           3
6       Carcinogenesis_v1     0.94           6
7                Chess_v1     0.25           2
8            Countries_v1     9.93           4
9                  DCG_v1     0.25           2
10               Dunur_v1     0.01          17
11                Elti_v1     0.05          11
12                FNHK_v1   120.00           3
13            Facebook_v1     1.38           2
14       Hepatitis_std_v1     0.68           7
15                Mesh_v1     0.04          29
16       Mooney_Family_v1     0.10          68
17           MuskSmall_v1     0.64           2
18                 NBA_v1     0.15           4
19                NCAA_v1    27.15           9
20                 PTE_v1     0.95          38
21                Pima_v1     0.11           9
22       PremierLeague_v1    17.20           4
23          Pyrimidine_v1     0.02           2
24                 SAP_v1   148.44           4
25                 SAT_v1     0.32          36
26             SalesDB_v1   269.25           4
27            Same_gen_v1     0.04           4
28        Student_loan_v1     0.09          10
29             Telstra_v1     3.87           5
30          Toxicology_v1     1.03           4
31            Triazine_v1     0.12           2
32         TubePricing_v1     9.67          20
33               UTube_v1     0.11           2
34              UW_std_v1     0.02           4
35               WebKP_v1     1.96           3
36      airbnb-simplified   293.14           2
37            fake_hotels     0.05           2
38   fake_hotels_extended     0.07           2
39           financial_v1    85.38           8
40                 ftp_v1     4.68           2
41               genes_v1     0.36           3
42           got_families     0.00           3
43      imdb_MovieLens_v1    39.20           7
44            imdb_ijs_v1   173.90           7
45          imdb_small_v1     0.15           7
46           legalActs_v1   130.30           5
47         mutagenesis_v1     0.37           3
48             nations_v1     0.45           3
49            restbase_v1     0.69           3
50               rossmann    73.33           2
51              trains_v1     0.01           2
52          university_v1     0.01           5
53                walmart    14.64           3
54               world_v1     0.23           3

**Download Demo**

In [7]:
from sdv.datasets.demo import download_demo
real_data,metadata=download_demo(
    modality='multi_table',
    dataset_name='fake_hotels'
)

**HMASynthesizer**

In [8]:
from sdv.multi_table import HMASynthesizer
synthesizer = HMASynthesizer(metadata)
synthesizer.fit(real_data)

Preprocess Tables:   0%|          | 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/rdt/transformers/pii/anonymizer.py:118: FutureWarning: The 'enforce_uniqueness' parameter is no longer supported. Please use the 'cardinality_rule' parameter instead.
  warnings.warn(
Preprocess Tables: 100%|██████████| 2/2 [00:00<00:00,  6.50it/s]

Learning relationships:

(1/1) Tables 'hotels' and 'guests' ('hotel_id'): 100%|██████████| 10/10 [00:05<00:00,  1.94it/s]

Modeling Tables: 100%|██████████| 2/2 [00:04<00:00,  2.36s/it]

**Samples**

In [11]:
synthetic_data=synthesizer.sample()
synthetic_data

{'hotels':   hotel_id           city          state  rating classification
 0  HID_000         Boston     California     3.8          CHAIN
 1  HID_001  San Francisco     California     4.5         RESORT
 2  HID_002  San Francisco  Massachusetts     4.5          MOTEL
 3  HID_003         Austin     California     4.5          CHAIN
 4  HID_004  San Francisco  Massachusetts     4.4         RESORT
 5  HID_005         Boston  Massachusetts     NaN         RESORT
 6  HID_006  San Francisco  Massachusetts     3.9          CHAIN
 7  HID_007  San Francisco     California     4.3          CHAIN
 8  HID_008         Boston       New York     4.5          CHAIN
 9  HID_009  San Francisco     California     3.8         RESORT,
 'guests':                        guest_email hotel_id  has_rewards room_type  \
 0            moodyeric@example.net  HID_000        False     BASIC
 1           coryguzman@example.com  HID_000        False     BASIC
 2           caitlinlee@example.net  HID_000        False     BASIC
 3          andreasmith@example.net  HID_000        False     BASIC
 4        fostermichael@example.com  HID_000        False     BASIC
 ..                             ...      ...          ...       ...
 653      maciasbradley@example.com  HID_009        False     BASIC
 654            sarah81@example.org  HID_009        False     BASIC
 655       thomasjustin@example.net  HID_009        False     SUITE
 656       grahamkaylee@example.net  HID_009         True     BASIC
 657  pattersonnicholas@example.com  HID_009        False    DELUXE

      amenities_fee checkin_date checkout_date  room_rate  \
 0            29.93  14 Sep 2020   23 Sep 2020      82.66
 1             3.90  21 Apr 2020   11 May 2020     104.87
 2             4.52  23 Sep 2020   10 Oct 2020     124.86
 3             2.28  17 Sep 2020   02 Oct 2020      88.28
 4             5.18  21 Dec 2020   27 Nov 2020      75.76
 ..             ...          ...           ...        ...
 653          11.68  03 Aug 2020   11 Jul 2020      91.10
 654           5.77  26 Nov 2020   02 Nov 2020     190.32
 655           0.80  20 Nov 2020   29 Oct 2020     105.28
 656           0.28  08 Feb 2020   22 Jan 2020     131.89
 657          29.05  03 Sep 2020   09 Aug 2020     204.00

                                        billing_address   credit_card_number
 0                     PSC 4273, Box 0888\nAPO AA 28423     5161033759518983
 1        417 Lawrence Hollow\nEast Ericshire, IN 65660  4133047413145475690
 2    69754 Mcguire Haven Apt. 260\nCrawfordside, IN...        4977328103788
 3         959 Copeland Drive\nLake Kellyport, PA 61063     3524946844839485
 4        496 Lynn Isle Suite 560\nTeresaport, OK 89054  4446905799576890978
 ..                                                 ...                  ...
 653          429 Doyle Port\nEast Laurenfurt, AL 19510  4326341462385878116
 654  976 Travis Shoals Apt. 973\nSchwartzburgh, IL ...       30039118593617
 655  6553 Wood Forest Suite 953\nKelseymouth, MS 69501     3512584462498997
 656  75125 James Turnpike Apt. 512\nMorrisonburgh, ...      180035651948687
 657  57190 Harris Plaza Suite 716\nWest Seanmouth, ...     6011276391394541

 [658 rows x 10 columns]}

**Scaling more.**

In [15]:
synthetic_data = synthesizer.sample(
    scale=1.5
)

In [16]:
synthetic_data

{'hotels':    hotel_id           city           state  rating classification
 0   HID_010    Los Angeles      California     4.9          MOTEL
 1   HID_011    Los Angeles        New York     NaN          CHAIN
 2   HID_012  San Francisco   Massachusetts     4.9         RESORT
 3   HID_013    Los Angeles           Texas     3.9          MOTEL
 4   HID_014  San Francisco  Massachuesetts     4.9          CHAIN
 5   HID_015         Austin      California     4.9         RESORT
 6   HID_016  San Francisco      California     4.2         RESORT
 7   HID_017    Los Angeles           Texas     NaN          MOTEL
 8   HID_018  New York City      California     4.3          MOTEL
 9   HID_019         Boston   Massachusetts     4.8         RESORT
 10  HID_020         Boston   Massachusetts     4.2         RESORT
 11  HID_021         Austin        New York     4.0          MOTEL
 12  HID_022         Austin      California     4.5          CHAIN
 13  HID_023         Austin   Massachusetts     4.5         RESORT
 14  HID_024         Boston   Massachusetts     4.3         RESORT,
 'guests':                        guest_email hotel_id  has_rewards room_type  \
 0         graceramirez@example.net  HID_010        False     BASIC
 1              grant15@example.com  HID_010        False    DELUXE
 2              xflores@example.net  HID_010        False     BASIC
 3        robertjohnson@example.org  HID_010        False     BASIC
 4             miguel20@example.net  HID_010        False     BASIC
 ..                             ...      ...          ...       ...
 982           amyhanna@example.com  HID_024        False    DELUXE
 983     tuckermichelle@example.com  HID_024        False     BASIC
 984            ospence@example.com  HID_024        False     BASIC
 985           lwallace@example.com  HID_024        False     BASIC
 986  fitzpatrickrachel@example.com  HID_024        False     BASIC

      amenities_fee checkin_date checkout_date  room_rate  \
 0            32.20  13 Jan 2020   04 Feb 2020     167.53
 1            24.16  22 Mar 2020   09 May 2020     197.02
 2            33.51  25 Feb 2020   14 Apr 2020     224.87
 3              NaN  07 Jul 2020   11 May 2020     227.76
 4            38.34  06 Jan 2020   10 Jan 2020     230.33
 ..             ...          ...           ...        ...
 982           0.29  17 Jul 2020   27 Aug 2020     238.27
 983           1.93  23 Nov 2020   29 Nov 2020     111.41
 984           1.90  04 Mar 2020   17 Apr 2020     132.00
 985           0.46  01 Feb 2020   04 Mar 2020     251.69
 986            NaN  10 Feb 2020           NaN     137.67

                                        billing_address  credit_card_number
 0       362 Williams Crossroad\nDeborahshire, TX 78084    6507393048786622
 1         81460 Joel Trail\nNew Melindaburgh, PW 45380      30545570648244
 2    4869 Burton Forks Apt. 907\nSouth Holly, NM 07352    2230036946683895
 3        7870 Romero Trafficway\nLisaborough, TX 24846       4692739982999
 4    19077 Adams Terrace Apt. 019\nPort Madeline, M...    3515432170279142
 ..                                                 ...                 ...
 982            454 Heidi Villages\nJamesberg, MS 62380    4143922902750426
 983     753 Brian Grove Apt. 589\nEast Amber, MH 89185    6563288768350578
 984     732 Jesus Walk Suite 312\nLake James, AK 65217       4503227690848
 985           818 Raymond Key\nNew Paulshire, KY 94249      30266983907081
 986                           USNV White\nFPO AE 13386    6011130925610254

 [987 rows x 10 columns]}

**Reset the sampling.**

In [17]:
synthesizer.reset_sampling()
synthetic_data2 = synthesizer.sample(scale=1.5)

In [18]:
synthetic_data2

{'hotels':    hotel_id           city           state  rating classification
 0   HID_000         Boston      California     3.8          CHAIN
 1   HID_001  San Francisco      California     4.5         RESORT
 2   HID_002  San Francisco   Massachusetts     4.5          MOTEL
 3   HID_003         Austin      California     4.5          CHAIN
 4   HID_004  San Francisco   Massachusetts     4.4         RESORT
 5   HID_005         Boston   Massachusetts     NaN         RESORT
 6   HID_006  San Francisco   Massachusetts     3.9          CHAIN
 7   HID_007  San Francisco      California     4.3          CHAIN
 8   HID_008         Boston        New York     4.5          CHAIN
 9   HID_009  San Francisco      California     3.8         RESORT
 10  HID_010    Los Angeles      California     4.9          MOTEL
 11  HID_011    Los Angeles        New York     NaN          CHAIN
 12  HID_012  San Francisco   Massachusetts     4.9         RESORT
 13  HID_013    Los Angeles           Texas     3.9          MOTEL
 14  HID_014  San Francisco  Massachuesetts     4.9          CHAIN,
 'guests':                    guest_email hotel_id  has_rewards room_type  amenities_fee  \
 0        moodyeric@example.net  HID_000        False     BASIC          29.93
 1       coryguzman@example.com  HID_000        False     BASIC           3.90
 2       caitlinlee@example.net  HID_000        False     BASIC           4.52
 3      andreasmith@example.net  HID_000        False     BASIC           2.28
 4    fostermichael@example.com  HID_000        False     BASIC           5.18
 ..                         ...      ...          ...       ...            ...
 982        qkeller@example.org  HID_014        False     BASIC           2.45
 983        david58@example.com  HID_014        False     BASIC          27.50
 984     randyfrank@example.org  HID_014         True     BASIC           0.91
 985      wendyyang@example.com  HID_014        False    DELUXE           1.86
 986      marialang@example.net  HID_014        False     BASIC           4.80

     checkin_date checkout_date  room_rate  \
 0    14 Sep 2020   23 Sep 2020      82.66
 1    21 Apr 2020   11 May 2020     104.87
 2    23 Sep 2020   10 Oct 2020     124.86
 3    17 Sep 2020   02 Oct 2020      88.28
 4    21 Dec 2020   27 Nov 2020      75.76
 ..           ...           ...        ...
 982  13 Jan 2020   12 Feb 2020     102.51
 983  23 Feb 2020   16 Mar 2020     224.08
 984  16 Dec 2020   07 Jan 2021     105.69
 985  17 Jan 2020   28 Feb 2020     194.81
 986  26 Feb 2020           NaN     155.84

                                        billing_address   credit_card_number
 0                     PSC 4273, Box 0888\nAPO AA 28423     5161033759518983
 1        417 Lawrence Hollow\nEast Ericshire, IN 65660  4133047413145475690
 2    69754 Mcguire Haven Apt. 260\nCrawfordside, IN...        4977328103788
 3         959 Copeland Drive\nLake Kellyport, PA 61063     3524946844839485
 4        496 Lynn Isle Suite 560\nTeresaport, OK 89054  4446905799576890978
 ..                                                 ...                  ...
 982  49674 Ronald Trafficway\nLake Aprilhaven, AK 2...         676175758694
 983                   Unit 8471 Box 3603\nDPO AA 52763         501800719723
 984          14523 Lynn Roads\nLake Michelle, NC 85020      373476575023495
 985           9193 George Island\nAaronshire, AS 37218       30083538335761
 986  15117 Martinez Spring Apt. 142\nNorth Arthur, ...     4090391564908180

 [987 rows x 10 columns]}

**Dictionary Form DataSets.**